---
- name: Upgrade packages to latest
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes
  register: upgrade_status
  notify:
    - Reboot

- name: Disable unattended upgrades
  apt:
    name: unattended-upgrades
    state: absent
